version: '2'

services:
  app:
    image: bugfire/aiseg_watch:0.1.4
    volumes:
      - "/share/Docker/Volumes/aiseg_watch/config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.13.11:514"
        syslog-format: "rfc3164"
        tag: "aiseg_watch"
